### ISSUE TITLE
Angular 17.3.1 build fails "Error: export (imported as ) was not found in ..."

### ISSUE THREAD

**Issue by andreibereczki** [bpmn-io/bpmn-js#2120] opened 2024-03-21 19:12 UTC
### Describe the Bug

In an Angular project, when using the bpmn-js library, i get the following errors on build:

Warning: C:/project/node_modules/diagram-js/lib/features/palette/PaletteProvider.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/project/node_modules/diagram-js/lib/model/Types.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/project/node_modules/diagram-js/lib/util/Types.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:597:19-30 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:781:19-30 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:837:19-30 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:898:19-30 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:932:19-30 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:974:19-30 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1022:21-32 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1175:21-32 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1242:15-20 - Error: export 'getDi' (imported as 'getDi') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1324:21-32 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1325:13-18 - Error: export 'getDi' (imported as 'getDi') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1396:21-32 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1442:21-32 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1520:21-32 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1525:29-40 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1585:21-32 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/draw/BpmnRenderer.js:1633:21-32 - Error: export 'getSemantic' (imported as 'getSemantic') was not found in './BpmnRenderUtil' (possible exports: black, getBounds, getCirclePath, getDiamondPath, getFillColor, getHeight, getLabelColor, getRectPath, getRoundRectPath, getStrokeColor, getWidth, isCollection, isThrowEvent, isTypedEvent, white)

./node_modules/bpmn-js/lib/features/auto-place/BpmnAutoPlaceUtil.js:27:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/context-pad/ContextPadProvider.js:216:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/context-pad/ContextPadProvider.js:331:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/context-pad/ContextPadProvider.js:358:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/distribute-elements/BpmnDistributeElements.js:26:29-34 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/grid-snapping/BpmnGridSnapping.js:14:8-13 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/label-editing/LabelEditingProvider.js:105:17-22 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/label-editing/LabelEditingProvider.js:142:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/label-editing/LabelEditingProvider.js:253:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/BpmnFactory.js:28:9-14 - Error: export 'isAny' (imported as 'isAny') was not found in './util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/BpmnFactory.js:49:13-18 - Error: export 'isAny' (imported as 'isAny') was not found in './util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/BpmnUpdater.js:156:45-50 - Error: export 'isAny' (imported as 'isAny') was not found in './util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/ElementFactory.js:158:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/ElementFactory.js:361:9-14 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/behavior/AttachEventBehavior.js:76:28-33 - Error: export 'isAny' (imported as 'isAny') was not found in '../util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/behavior/DataStoreBehavior.js:113:8-13 - Error: export 'isAny' (imported as 'isAny') was not found in '../util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/behavior/IsHorizontalFix.js:23:8-13 - Error: export 'isAny' (imported as 'isAny') was not found in '../util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/behavior/RootElementReferenceBehavior.js:37:11-16 - Error: export 'isAny' (imported as 'isAny') was not found in '../util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/behavior/RootElementReferenceBehavior.js:58:8-13 - Error: export 'isAny' (imported as 'isAny') was not found in '../util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/modeling/behavior/RootElementReferenceBehavior.js:66:8-13 - Error: export 'isAny' (imported as 'isAny') was not found in '../util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/ordering/BpmnOrderingProvider.js:93:13-18 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/ordering/BpmnOrderingProvider.js:112:10-15 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/ordering/BpmnOrderingProvider.js:124:31-33 - Error: export 'is' (imported as 'is') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/replace/BpmnReplace.js:217:8-13 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/replace/BpmnReplace.js:217:105-110 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:157:9-14 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:432:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:454:11-16 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:468:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:469:11-16 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:848:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:848:80-85 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:853:6-11 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:853:80-85 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/rules/BpmnRules.js:883:9-14 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/snapping/BpmnConnectSnapping.js:57:10-15 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

./node_modules/bpmn-js/lib/features/snapping/BpmnConnectSnapping.js:62:10-15 - Error: export 'isAny' (imported as 'isAny') was not found in '../modeling/util/ModelingUtil' (possible exports: getParent)

### Steps to Reproduce

1. install angular 17.3.1
2. add bpmn-js as dependency
3. import bpmn-js
4. initialize Modeler

### Expected Behavior

none of the above import errors should appear

### Environment

 - Node v20.11.0
 - Npm v10,2,4
 - OS: Windows 11
 - Library version: 17.1.0

**Comment by nikku** [comment] 2024-03-22 08:33
@andreibereczki If you share with us a simple setup that reproduces this issue then we can look into this.

At this stage it could be anything from old typescript version, Angular "optimizations" and/or an error in our typings in conjunction with Angular tooling (which are confirmed to work for standard setups).

**Comment by nikku** [comment] 2024-04-15 16:07
Closing as _cannot reproduce_.

**Closed** 2024-04-15 16:07 UTC
Labels: bug, needs more information
