### ISSUE TITLE
Focus is not cleared for parent element while attach boundary even in IE /Edge browser

### ISSUE THREAD

**Issue by chandishwarOptum** [bpmn-io/bpmn-js#1361] opened 2020-10-20 04:04 UTC
__Describe the Bug__

Focus is not cleared for parent element while attach boundary event in
IE /Edge browser only,
in Chrome it is working fine

Edge version (40.150)
IE Browser version (11):

__Steps to Reproduce__

1. add UserTask /ServiceTask 
2. attach boundary event to UserTask /ServiceTask

__Expected Behavior__

__Environment__

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

**Comment by MaxTru** [comment] 2020-10-20 06:55
Thanks for reporting this. Before we try to reproduce, could you please explain whether there is a specific need for you to use Edge 40.150 or IE 11? 

Do you have the option to use the latest stable version of legacy Edge (44.190 if I am not mistaken)? If so, do you experience the same issue there?

**Comment by barmac** [comment] 2020-10-20 15:17
I couldn't reproduce it on legacy Edge 44.

![edge](https://user-images.githubusercontent.com/28307541/96606602-bfdbb080-12f7-11eb-8d9b-6f96b4859204.gif)

**Comment by nikku** [comment] 2020-11-02 11:58
Closing this one as we did not receive a follow up and [could not reproduce](https://github.com/bpmn-io/bpmn-js/issues/1361#issuecomment-712928346), too.

Please provide us with the requested details and we are happy to re-open this issue.

**Closed by nikku** 2020-11-02 11:58 UTC
Labels: bug
