### ISSUE TITLE
labels in sub process visible in parent process after collapse

### ISSUE THREAD

**Issue by adbre** [bpmn-io/bpmn-js#1262] opened 2020-01-06 09:34 UTC
__Describe the Bug__

Labels within a sub process are visible in parent process canvas even after the sub process is collapsed, after the "create/remove space" tool has been used to move label.

__Steps to Reproduce__

1. Create a expanded sub process
2. Add a label "Hello" (can be anything) to the default start event in the sub process
4. Activate the create/remove space tool and start by clicking between the space between the left border of the sub process and the default sub process.
5. Drag to the left, so the start event (and associated label) is moved to the left.
6. Do not drag too much, the start event (and associated label) must not "touch" the sub process b
order. Just being moved closer to it.
7. Collapse the sub process.
8. The label "Hello" is now visible in the parent canvas, and outside the collapsed sub process

![visible-label](https://user-images.githubusercontent.com/1292956/71810501-d10e4600-3072-11ea-9c4f-66c9b5f298da.gif)

__Expected Behavior__

Labels belonging to a sub process should not be visible if the sub process is collapsed.

__Environment__

 - Browser: Firefox 71.0
 - OS: Windows 10
 - demo.bpmn.io/new as of 6 january 2020

**Comment by nikku** [comment] 2020-01-06 12:20
Thanks for the report!

How important is expanding / collapsing sub-processes for you?

**Comment by adbre** [comment] 2020-01-06 12:39
I interpreted your question in two ways.

How important is a bug fix?
How important is the feature of collapsing sub processes, generally?

I'll answer both.

We are using bpmn-js embedded, and have limited some objects we are not
currently supporting in processing. Sub processes are currently not
supported, though we would like to. But not yet included in roadmap.

So this bug is not a problem at all for us now.

Expanding and collapse sub processes, I imagine, will be very useful for us
since the models are often large. But that's really speculation since we
don't use it.

Still, I wanted to report it when I stumbled upon it in the demo site.

Den mån 6 jan. 2020 13:20Nico Rehwaldt <notifications@github.com> skrev:

**Comment by nikku** [comment] 2020-01-08 10:15
Thanks for clarifying. If you are still considering adding sub-processes I recommend you to disallow collapsing all together (cf. [bpmn-io/bpmn-js-disable-collapsed-subprocess](https://github.com/bpmn-io/bpmn-js-disable-collapsed-subprocess)).

Let me elaborate on the reason: This issue is just one of many issues with collapsing sub-processes. The biggest issue in the collapse/expand realm however is how to handle (re-) expanding. With no automatic layouting in place the user is pretty much left with a big amount of re-layouting labor after any collapse / expand operation.

This is the reason why we discourage collapsing and expanding sub-processes.

A couple of viable alternatives exist:

* Only allow expanding (cf. library mentioned above)
* Allow calling _external_ processes via BPMN call activities and linking to them in the diagram

**Comment by nikku** [comment] 2020-01-08 10:16
Closing this as a duplicate of https://github.com/bpmn-io/bpmn-js/issues/945.

**Closed by nikku** 2020-01-08 10:16 UTC
Labels: backlog, bug
