### ISSUE TITLE
typographical errors in chrome

### ISSUE THREAD

**Issue by yanyim** [bpmn-io/bpmn-js#697] opened 2017-07-25 03:30 UTC
<img width="919" alt="f6790fd9-8580-43d8-994e-0edb39ab59e8" src="https://user-images.githubusercontent.com/5211242/28554567-bfe90f5c-712c-11e7-924f-c86320cb77dc.png">
In the chrome browser, load bpmn xml for the first time. All of the start event, end event, gateway, will be typographical errors, focus to the top left corner.

**Comment by pedesen** [comment] 2017-07-25 07:46
Hi yanyim. Which chrome version are you using? And where exactly do you experience these issues (for example on http://demo.bpmn.io)? Did you make any changes to the code or the diagram?

**Comment by yanyim** [comment] 2017-07-26 03:00
Today I upgraded the chrome version to 60.0.3112.78 (official version) (64-bit), this problem no longer exists. The program is correct. thank you for your reply.

The chrome version of the problem is 57.0.2987.110 (64-bit), I have not modified the program, I just run the example program only. I have visited an earlier version of the example, and there is no problem. But I can not confirm the version he used.

**Comment by pedesen** [comment] 2017-07-26 08:23
There was a bug in Chrome 57 regarding SVG rendering. We implemented a temporary hotfix back then: https://github.com/bpmn-io/bpmn-js/issues/673
Since the issue is fixed in Chrome 58+ we reverted the hotfix, because it is working fine again with the current Chrome version.

**Closed by pedesen** 2017-07-26 08:23 UTC
