### ISSUE TITLE
Attrs are not copied

### ISSUE THREAD

**Issue by victornikitin** [bpmn-io/bpmn-js#905] opened 2018-11-16 15:14 UTC
When I try to copy element, custom attributes are not copied.

Original element xml:
```
<camunda:inputOutput>
  <camunda:outputParameter name="i" configName="vars">
    <camunda:script scriptFormat="JavaScript">
      <![CDATA[ {"type":"script","value":"0"} ]]>
    </camunda:script>
  </camunda:outputParameter>
</camunda:inputOutput>
```

After paste it is without attr configName:
```
<camunda:inputOutput>
  <camunda:outputParameter name="i">
    <camunda:script scriptFormat="JavaScript">
      <![CDATA[ {"type":"script","value":"0"} ]]>
    </camunda:script>
  </camunda:outputParameter>
</camunda:inputOutput>
```

I'm using BPMN-JS version 0.20.7
I've tested it on last version too. The same error.

**Comment by barmac** [comment] 2018-11-19 15:22
Can you please provide a test case which reproduces the invalid behaviour?

**Comment by pinussilvestrus** [comment] 2018-12-04 13:34
@victornikitin Any more input regarding this? 

I'm going to close this since the bug couldn't be reproduced without any extra information. You can reopen it if it's still relevant for you.

**Closed by pinussilvestrus** 2018-12-04 13:34 UTC
Labels: help wanted
