### ISSUE TITLE
Integrate vertical pools / lanes for better readability

### ISSUE THREAD

**Issue by sfelix39** [bpmn-io/bpmn-js#1494] opened 2021-09-25 14:46 UTC
__Is your feature request related to a problem? Please describe.__
A simple readability of bpmn models is limited by the width and height of the screen where it's represented. 
Of course scrolling (vertical, horizontal) could solve this problem.
Especially horizontal scrolling isn't the regular way to navigate through a lot of information, for example as a bpmn model gives.
Imagine a spreadsheed which represents its information in a horizontal way or a scientific paper which uses a horizontal orientation. All represented informations might be there in a readable menor, but it feels wrong to scroll left and right to view the given information.
The same situation happens when larger bpmn models with less participants have to be represented horizontal, especially when the model will be exported and embedded in a wiki-like System.
A vertical orientation of models would help to improve the readability of bmpn models especially in wiki-like Systems, because a lot of space on the right on the screen would be saved. The information given by the model could be read better by common vertical scrolling.

__Describe the solution you'd like__
Enable vertival orientation of pools and lanes.
Not just the rendering of labels (#57) or the import of given models which includes vertical lanes (#1482), moreover the explicit creation of vertical pools and lanes should be supported.

__Possible Tasks to integrate vertical lanes & pools__
- [ ] create a opportunity to rotate a vertical pool in a horizontal one (and vice versa)
- [ ] create a opportunity to add horizontal lanes to horizontal pools
- [ ] load bpmn models with vertical lanes & pools
- [ ] store bpmn models with vertical lanes & pools

I read that vertical lanes aren't on your roadmap but you're open for PRs, so i want to contribute to this feature.

**Comment by barmac** [comment] 2021-10-04 06:26
> I read that vertical lanes aren't on your roadmap but you're open for PRs, so i want to contribute to this feature.

Please feel free to contribute a PR with the feature. Mind to follow our [contributing guidlines]. 

As this issue is a duplicate of https://github.com/bpmn-io/bpmn-js/issues/507, I will close it. However, we are happy to merge a PR with a contribution.

**Closed by barmac** 2021-10-04 06:26 UTC
Labels: enhancement
