### ISSUE TITLE
Selecting events and gateways makes some elements smaller than normal or to disappear

### ISSUE THREAD

**Issue by vcpablo** [bpmn-io/bpmn-js#1294] opened 2020-03-16 18:49 UTC
__Describe the Bug__

Completing direct editing with an empty label resizes the label target to minimum bounds:

![capture ZnZ8sj_optimized](https://user-images.githubusercontent.com/58601/77805963-a0dbaf80-7083-11ea-98f3-ba5183a2af78.gif)

This can be reproduced on demo.bpmn.io, too.

__Steps to reproduce__

1. Start direct editing on element with external label.
2. Complete direct editing with empty text

---

This broke via https://github.com/bpmn-io/bpmn-js/commit/e4e789bd3eecc47597d97d6c8f1e71b941dee066#diff-642682e3de745f747ccb55e702973a89L107.

----

__Describe the Bug__

After clicking on an event (of any kind) or a gateway (of any kind) the shapes of the elements change quickly and become smaller and not clickable (the gateway elements even disappear). This bug happened after I upgraded from version 6.3.0 to 6.3.3

Here is an image demonstrating what happens to the quoted elements
![image](https://user-images.githubusercontent.com/4389464/76790330-67f72d00-679d-11ea-9423-83ff91f27e43.png)

__Steps to Reproduce__

1. Import a BPMN XML to the tool
2. Click on an element (to select it) which type is: event or gateway

**Obs: By selecting the elements using the Lasso Tool, this bug does not happen**

__Expected Behavior__

The elements must not change its shape or disappear when clicked, see example below (screenshot from demo.bpmn.io

![image](https://user-images.githubusercontent.com/4389464/76790539-ccb28780-679d-11ea-9bc9-59a6ca0d0263.png)

__Environment__

 - Browser: Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)
 - OS: MacOS Catalina 10.15.3
 - Library version: 6.3.3

**Comment by nikku** [comment] 2020-03-16 20:44
I cannot reproduce this issue locall as well as [on our demo](https://demo.bpmn.io):

![capture 81fp5l_optimized](https://user-images.githubusercontent.com/58601/76798057-1f586780-67cf-11ea-9123-07c47630592d.gif)

Please spend some time to [understand the changes since the upgrade](https://github.com/bpmn-io/bpmn-js/compare/v6.3.0...v6.3.3) and provide some additional context how you use the toolkit.

**Comment by nikku** [comment] 2020-03-27 22:37
I am able to reproduce the issue on demo.bpmn.io.

It is not about selecting but about completing direct editing with an empty label. That resizes the element accidentally to the empty labels bounds (width `0px`):

![capture ZnZ8sj_optimized](https://user-images.githubusercontent.com/58601/77805963-a0dbaf80-7083-11ea-98f3-ba5183a2af78.gif)

#### Steps to reproduce

1. Start direct editing on element with external label.
2. Complete direct editing with empty text

This broke via https://github.com/bpmn-io/bpmn-js/commit/e4e789bd3eecc47597d97d6c8f1e71b941dee066#diff-642682e3de745f747ccb55e702973a89L107.

**Comment by nikku** [comment] 2020-03-27 22:41
Updated the issue description accordingly.

**Comment by vcpablo** [comment] 2020-03-29 16:15
Thanks @nikku nice to know you were able to reproduce it.

**Comment by nikku** [comment] 2020-03-30 08:55
Closed via https://github.com/bpmn-io/bpmn-js/pull/1299.

**Closed by nikku** 2020-03-30 08:55 UTC
Labels: bug, needs review
