### ISSUE TITLE
No arrow tip on sequence flows in Safari

### ISSUE THREAD

**Issue by nevries** [bpmn-io/bpmn-js#1124] opened 2019-07-09 08:58 UTC
__Describe the Bug__

There are no arrow tips rendered in Safari.

__Steps to Reproduce__

1. Open Safari
2. Browse to https://demo.bpmn.io/new
3. Draw some sequence flow

![noArrowTip](https://user-images.githubusercontent.com/31620219/60874537-7f5a3f80-a238-11e9-9ef2-b3c1ace07685.gif)

__Expected Behavior__

I see a sequence flow with arrow tip.

__Environment__

Please complete the following information:

 - Browser: Safari 12.1.1 (14607.2.6.1.1)
 - OS: mac os 10.14.5 (18F132)

**Comment by nikku** [comment] 2019-07-09 09:48
Duplicate of https://github.com/bpmn-io/bpmn-js/issues/1120.

Do you see this only on the demo or other places that use bpmn-js?

**Closed by nikku** 2019-07-09 09:48 UTC
Labels: duplicate
