### ISSUE TITLE
Half of the diagram becomes hidden after editing Task 

### ISSUE THREAD

**Issue by VictorMalcov** [bpmn-io/bpmn-js#1363] opened 2020-10-27 17:44 UTC
Issue: BPMN diagram disappears after editing Task node.

To replicate:

1. Open codepen example: https://codepen.io/york2k/pen/qBNrLxK 
2. Double click on Task “Select a Pizza” and change name to something.
3. Click outside of the task to finish editing name.
4. Move mouse cursor over diagram, and bottom half diagram disappears.

In Edge Chromium, the diagram is broken without editing Task. Just move mouse over diagram and some lines will become bold.

**The issue is when using BPMN container inside flex boxes.**

Thanks

Environment:
 - Chrome (latest), Edge Chromium (latest), Firefox (latest)
 - OS: Windows 10
 - Library version: bpmn-js@6.0.0-beta.0

**Comment by VictorMalcov** [comment] 2020-10-27 17:59
My temporary solution is to set following styles to `<div id=canvas></div>`:

`position: absolute; top:0; bottom:0; left:0; right:0`

**Comment by nikku** [comment] 2020-11-02 11:53
Thanks for filing this bug report. 

Could you update your report to use our existing issue template for bugs? Specifically we ask you in there about the expected behavior. What do you expect in this case? How do you expect sizing of the diagram element to work?

> In Edge Chromium, the diagram is broken without editing Task. Just move mouse over diagram and some lines will become bold.

Lines becoming bold is due to the fact that you miss the diagram stylesheet (cf. [example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/pre-packaged#modeler)).

**Comment by pinussilvestrus** [comment] 2020-11-06 10:48
@VictorMalcov any updates?

**Comment by yuejiangming** [comment] 2020-11-09 08:08
> @VictorMalcov any updates?

Same question and recovered temporarily with his method

**Comment by VictorMalcov** [comment] 2020-11-18 04:47
@pinussilvestrus , @yuejiangming 
Hi, 
No updates from me. I am planning to use this "fix" till somebody fixes this bug.

**Comment by nikku** [comment] 2020-11-18 09:36
Closing this as it may be a browser glitch according to https://github.com/bpmn-io/bpmn-js/issues/1363#issuecomment-723842047.

**Comment by nikku** [comment] 2020-11-18 09:37
Hopefully temporary workaround: https://github.com/bpmn-io/bpmn-js/issues/1363#issuecomment-717421524.

**Closed by nikku** 2020-11-18 09:36 UTC
Labels: bug, help wanted
