### ISSUE TITLE
Groups in empty diagram cause errors

### ISSUE THREAD

**Issue by BelindaBecker** [bpmn-io/bpmn-js#1133] opened 2019-07-25 10:11 UTC
__Describe the Bug__

After adding a group to an empty diagram, the editor crashes when trying to add other elements.

__Steps to Reproduce__

on https://demo.bpmn.io/new
1. Open the empty/initial diagram
2. delete the start event
3. add a group
4. add for example a pool

Result: the console throws a lot of errors and the editor gets stuck.

![bpmn_group_bug](https://user-images.githubusercontent.com/51420727/61866021-ad947c00-aed4-11e9-9b2c-cd49d7d07ab3.gif)
![groups_error](https://user-images.githubusercontent.com/51420727/61866028-af5e3f80-aed4-11e9-9c8b-4eb7f190bb5a.PNG)

__Expected Behavior__

It should be possible to keep on modeling.

__Environment__

Please complete the following information:

 - Browser: Chrome  75.0.3770.142 
 - OS: Windows 10
 - Library version: The one deployed on https://demo.bpmn.io/new, should be bpmn-js 4.0.3

**Comment by nikku** [comment] 2019-07-25 10:21
Could you provide us with your logs, starting from the first error?

**Comment by nikku** [comment] 2019-07-25 10:25
On my machine (Arch Linux, your Chrome version) I cannot reproduce the issue given the steps you procided:

![capture 79d5GQ_optimized](https://user-images.githubusercontent.com/58601/61867350-47f5bf00-aed7-11e9-87db-d80fe5c9a459.gif)

**Comment by BelindaBecker** [comment] 2019-07-25 10:32
Sure! This is what I get from the brwoser console:
Topmost errors in trace:
![error_1](https://user-images.githubusercontent.com/51420727/61867609-e7b34d00-aed7-11e9-829f-31bc7d4c7e93.PNG)

Next Error: 
![error_2](https://user-images.githubusercontent.com/51420727/61867629-ee41c480-aed7-11e9-98d0-a809549ada11.PNG)

After this, the exactly same three errors are thrown multiple times. 
I am able to reproduce this every time I do the steps describe above..

**Comment by BelindaBecker** [comment] 2019-07-25 10:34
I did some more testing: the error occurs _only_ if you add a pool !

**Comment by nikku** [comment] 2019-07-25 11:26
Thanks for the additional clarification. I can reproduce it now. We will have a look. :+1:

**Comment by pinussilvestrus** [comment] 2019-08-02 14:24
Root-Cause: In [`CreateParticipantBehavior`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/behavior/CreateParticipantBehavior.js#L51) the childrenBBox has malformed (NaN) height and width properties, because `bpmn:Group` elements are ignored. If no other elements are there, of course, no children are still available to create the correct participant bounds.

**Comment by pinussilvestrus** [comment] 2019-08-05 10:07
Closed via 5d5f33c

**Closed by pinussilvestrus** 2019-08-05 10:07 UTC
Labels: bug, modeling, needs review
