### ISSUE TITLE
Rendering broken in Chrome 57

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#673] opened 2017-03-17 13:41 UTC
Rendering is broken in latest Chrome (57). 

SvgTranformUtil#translate does not work correctly anymore.

![unbenannt](https://cloud.githubusercontent.com/assets/7633572/24045610/f7f962ca-0b1f-11e7-9a8d-89484f393b59.PNG)

**Comment by philippfromme** [comment] 2017-03-17 13:46
Quick and dirty fix:

```
// SvgTransformUtil.js

module.exports.translate = function(gfx, x, y) {
  // var translate = createTransform();
  // translate.setTranslate(x, y);
  //
  // svgTransform(gfx, translate);

  gfx.setAttribute('transform','translate(' + x + ',' + y + ')');
};
```

**Comment by philippfromme** [comment] 2017-03-17 14:07
See [this issue](https://github.com/clientIO/joint/issues/535). Other people are experiencing problems with the SVGTransformList API, too.

**Comment by nikku** [comment] 2017-03-17 14:38
Duplicate of https://github.com/bpmn-io/bpmn-js/issues/671.

**Closed** 2017-03-17 15:27 UTC
Labels: bug, needs review

**Comment by nikku** [comment] 2017-03-17 21:04
Resize still seems to be broken:

![image](https://cloud.githubusercontent.com/assets/58601/24062900/a5c6a3bc-0b5d-11e7-976a-344e312d83dd.png)

(Works in FF).
