### ISSUE TITLE
Not working undo/redo for multi-instance

### ISSUE THREAD

**Issue by shibaaboy** [bpmn-io/bpmn-js#1960] opened 2023-09-26 11:52 UTC
Describe the Bug

When I set a Task or SubProcess as multi-instance and change the type (parallel or serial) and then use undo/redo, there is no visual change (parallel or serial is not shown).

Steps to Reproduce

Click on A Task
Mark it as multi-instance using the replace menu
Use undo/redo -> no visual change

https://github.com/bpmn-io/bpmn-js/assets/43315031/64032338-64a3-4305-a6bd-0bfd2e4f4ce7

**Comment by barmac** [comment] 2023-09-26 14:45
I cannot reproduce it at https://demo.bpmn.io/s/start

**Comment by shibaaboy** [comment] 2023-09-26 14:49
https://demo.bpmn.io/s/start - url
if i use undo/redo - no visual change (parallel or serial) 
<img width="583" alt="Снимок экрана 2023-09-26 в 17 47 51" src="https://github.com/bpmn-io/bpmn-js/assets/43315031/33f1f579-99e2-495b-8305-b08272c95e5c">
<img width="498" alt="Снимок экрана 2023-09-26 в 17 48 15" src="https://github.com/bpmn-io/bpmn-js/assets/43315031/6ef0a2d2-492b-49da-9da5-4a8a3e71285e">

Type icon doesn't change when i use undo/redo

**Comment by shibaaboy** [comment] 2023-09-26 14:56
1) add a task or subprocess
2) change type - parallel -> Task with icon
3) change type - serial -> Task with another icon
4) use undo (command + z) -> no visual change ( type must be parallel )
6) use undo (command + z) -> visual change ( without type )

when undo/redo changes in sequence types are not shown

**Comment by shibaaboy** [comment] 2023-09-26 15:01
@barmac Will this be fixed?

**Comment by barmac** [comment] 2023-09-26 15:03
We are happy to accept external contributions, but otherwise it's on our list.

**Comment by HodaSalim** [comment] 2023-09-29 18:04
Could you please assign this to me? I'm interested in taking it on. Are there any specific timelines for its completion or release?

**Comment by barmac** [comment] 2023-10-02 07:50
Hi, feel free to prepare a PR. As long as there is no `in progress` label, we are not working on this.

**Comment by nikku** [comment] 2023-10-12 12:05
Closed via https://github.com/bpmn-io/bpmn-js/issues/1970.

**Closed by nikku** 2023-10-12 12:05 UTC
Labels: bug, needs review, good first issue, pr welcome, spring cleaning, hacktoberfest

**Comment by shibaaboy** [comment] 2023-10-12 12:34
Will the bug be solved and in what version?

**Comment by shibaaboy** [comment] 2023-10-12 12:40
Thanks for the solution!
