### ISSUE TITLE
API document request

### ISSUE THREAD

**Issue by joker-yjc** [bpmn-io/bpmn-js#1160] opened 2019-08-12 06:34 UTC
Example demos are so one-sided，so maybe a detailed document about this will help more developer learn it better.
thanks

**Comment by nikku** [comment] 2019-08-12 06:55
What exactly do you need? What questions should the docs answer?

**Comment by joker-yjc** [comment] 2019-08-12 07:05
some default function that be provided by BpmnJS , for example this.bpmnModeler.get("modeling"),although I can do something by read the example-demo but it is hard to do more.

**Comment by nikku** [comment] 2019-08-12 08:53
The toolkit has 50000 lines of code and exposes around 100 services (internal and external). What exact use-case do you have in mind that will be fixed by documentation? In other words, if you had documentation, which question would you expect it would answer?

**Comment by nikku** [comment] 2019-08-13 08:42
Closing this as a duplicate of https://github.com/bpmn-io/bpmn-js/issues/332.

**Closed by nikku** 2019-08-13 08:42 UTC

**Comment by ehwest** [comment] 2019-08-23 18:29
Anyway someone could provide a docker container with everything loaded in, including web server, database, and whatever else is needed?  Save on Docker Hub.
I'm actually unable to install this on any server where I work, owing to proxy-enforced restrictions on various npm pieces.   But if this came in a Docker container, I could use it.

**Comment by nikku** [comment] 2019-08-25 18:08
You cannot serve [a simple HTML](https://github.com/bpmn-io/bpmn-js-examples/tree/master/starter) without using docker? If that is the case, this project is probably not the right one for you to use.
