### ISSUE TITLE
Need support for Angular 17 and 18

### ISSUE THREAD

**Issue by swethadmurthy2024** [bpmn-io/bpmn-js#2243] opened 2024-10-02 17:51 UTC
### Describe the Bug

1) unable to load BPMN file while using angular 18.2.6
2) With Angular 7.3.9, I have to use "npm install --force", which is not the best practice.

Please provide support for Angular 17 and 18

**Comment by barmac** [comment] 2024-10-03 07:09
Please check out the Angular example: https://github.com/bpmn-io/bpmn-js-example-angular

For the usage questions/problems, feel free to open a thread at https://forum.bpmn.io

**Comment by barmac** [comment] 2024-10-03 07:09
I am closing this issue as it's not a bug in bpmn-js.

**Closed by barmac** 2024-10-03 07:09 UTC
Labels: bug
