### ISSUE TITLE
Sequence Flow is not lost, when deleting an element

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-js#460] opened 2016-01-26 08:36 UTC
Given this situation

![image](https://cloud.githubusercontent.com/assets/3829733/12575879/5b969f1c-c410-11e5-9c1e-e217e458020f.png)

Let's delete the task in the middle

It currently looks like this after that

![image](https://cloud.githubusercontent.com/assets/3829733/12575901/7e17bf12-c410-11e5-8b15-6787866445ae.png)

It would be great, if we could keep the sequence flow (at least on of the two)
![image](https://cloud.githubusercontent.com/assets/3829733/12575918/9790ba3e-c410-11e5-8656-57b9f98857ef.png)

**Comment by nikku** [comment] 2016-01-26 08:36
What is this issue about?

**Comment by gimbel** [comment] 2016-01-26 08:40
Of course we need to clary under which conditions this would be possible and which sequence flow we would keep.

Proposal:
- Only works for elements with exactly one outgoing flow and exactly one incoming flow
- we keep the incoming flow

**Comment by nikku** [comment] 2016-01-26 09:25
Duplicate of #433?

**Closed** 2016-01-26 15:40 UTC
Labels: modeling
