### ISSUE TITLE
Listener for element removed, send element wrong

### ISSUE THREAD

**Issue by lucrod1** [bpmn-io/bpmn-js#952] opened 2019-03-25 14:42 UTC
__Describe the Bug__

When I change the type of an "Start event" to "Start timer event"
In this case the new elements are added and updated as necessary. (Wonderful)

But when I change the "Start timer event" type back to "Start event" again, the element callback does not tell the last element created but the start element in step1 (this element not exist more). As we can see in the image below.

__Steps to Reproduce__

![ezgif com-crop](https://user-images.githubusercontent.com/11089506/54928370-8c099080-4ef2-11e9-80cc-749203988e64.gif)

__Expected Behavior__

I expected the removal callback to correctly report the 2nd element that was removed, in this case, the StartEvent_0ub9bfb element as done in the first step.

__Environment__

Please complete the following information:

 - Browser: Version 72.0.3626.121 (Official Build) (64-bit)
 - OS: MAC OS MOJAVE 10.14.2
 - Library version: 3.2.2

**Comment by nikku** [comment] 2019-03-25 14:49
Thanks for your detailed report!

Could you build a small test case, either using our [existing test suite](https://github.com/bpmn-io/bpmn-js/blob/master/test/spec/features/modeling/DeleteShapeSpec.js) or based on our [modeler starter](https://github.com/bpmn-io/bpmn-js-examples/blob/master/starter/modeler.html) that reproduces the issue?

This makes it easier for us to reproduce the issue and eventually fix it.

**Comment by lucrod1** [comment] 2019-03-25 16:17
@nikku Can this be useful for now?


I'm using the same example of the starter kit
https://jsfiddle.net/3yn9x2ts/2/

![Screen Shot 2019-03-25 at 12 57 03 (2)](https://user-images.githubusercontent.com/11089506/54935679-8b2b2b80-4eff-11e9-9680-7520850ef53a.png)

Step: 
1 change type first Start event for Start Timer Event
2 change type again for Start event

this reproduce same print screen above 

it is possible to observe that the last callback shot is not the last element created, but the original, which has already been deleted.

**Comment by nikku** [comment] 2019-04-02 09:29
Thanks for the additional details. We'll have a look.

**Comment by pinussilvestrus** [comment] 2019-05-02 10:07
This expected behavior! We update the id of `newShape` to the id of the `oldShape` in bpmn-js as built-in modeling behavior (cf. [`ReplaceElementBehavior`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/ReplaceElementBehaviour.js#L75)). As you can see, it just updates the id _right after_ the `shape.added` is fired (cf. original firing in [Canvas.js](https://github.com/bpmn-io/diagram-js/blob/master/lib/core/Canvas.js#L555)). Therefore it seems, that every time a shape is replaced, the newShape got's a new id when you log it under `eventBus.on('shape.added')`, but it does not, since it got updated later on. Therefore every time, it deletes the element with the "old" id, but it's the correct one.

I know it's a bit confusing, but the ID-updating is a bpmn-js-only feature, so we have to check-in to the `shape.added` event at a later time via a modeling behavior.

Does this help you to understand what's going on? Just ask if you have additional thoughts about this. I'll close this issue since there is no real bug. You're welcome to re-open it if you have additional findings.

**Closed by pinussilvestrus** 2019-05-02 10:07 UTC
Labels: help wanted

**Comment by hzyhbk** [comment] 2019-07-24 01:30
@pinussilvestrus Hi, I have the same question about when the id of `newShape` will be updated. 
First of all, I add a `Task`, and its id is like `Task_0f9srn7`. And then, I changed the `Task` to `UserTask`. In my opinion, the id will change to like `UserTask_1br5kvx`,but it does not, it always  stay the same `Task_0f9srn7`. 

I saw the code snippet you pointed out at [ReplaceElementBehavior](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/ReplaceElementBehaviour.js#L75). It seems that the reason is that code `modeling.updateProperties(newShape, { id: oldShape.id });`, every time it use the `oldShape.id` to update the `newShape.id`, I do not understand why.

So, I want to ask when its id will be changed to a new one while the shape was changed.

**Comment by pinussilvestrus** [comment] 2019-08-01 06:49
It makes sense to NOT update the id for the replaced element when you think about dependencies and references between other elements. To overcome this expected behavior you will have to update the code yourself with a custom implementation.

**Comment by hzyhbk** [comment] 2019-08-01 09:14
> It makes sense to NOT update the id for the replaced element when you think about dependencies and references between other elements. To overcome this expected behavior you will have to update the code yourself with a custom implementation.

Thank you for your answer.  I understand the reason through your answer.  Will you support dynamic update the replaced element's id in the future?

**Comment by pinussilvestrus** [comment] 2019-08-01 09:32
The general question is: why do you need such functionality? Can you give us some scenarios in which this would be helpful?

This way we can understand where are the use cases and we can discuss whether to offer it some day.
