### ISSUE TITLE
Changing Task Type does not erase previously created exceptions

### ISSUE THREAD

**Issue by Carbammato** [bpmn-io/bpmn-js#1182] opened 2019-09-05 15:37 UTC
__Describe the Bug__

If I have a task of a defined type with some extensions selected via properties-panel, if I change the type to a different one the bpmn update the task type without clearing the extensions.

__Steps to Reproduce__

I created a simple model, with an user task where I give to user the chance to add some custom extensions. Doing that, the XML generated looks like this:

```
<bpmn2:userTask id="_manual_task" name="This is a manual task">
  <bpmn2:extensionElements>
     <dm:priority code="2" />
     <dm:category code="Category02" />
   </bpmn2:extensionElements>
   ...
</bpmn2:userTask>
```

Let’s imagine that I made a mistake, that should be a Manual Task (as Id and Name properties shows), so: right click with my mouse, click on wrench, select manual task. My bpmn looks like this:
after
While my XML looks like this:

```
<bpmn2:manualTask id="_manual_task" name="This is a manual task">
  <bpmn2:extensionElements>
    <dm:priority code="2" />
    <dm:category code="Category02" />
  </bpmn2:extensionElements>
  ...
</bpmn2:manualTask>
```

And this where I notice for this first time that a change of task do not clean up existing extensions. Priority and Category are not selectable in a manual Task so, in order to keep the code clean and avoid problems, I’ve to take them away.

Question: how can I do that?

I tried to find some solution by myself, especially with changedElement listener of eventBus, but that means that I risk to clean up extensions at any editing action. Does anybody has a suggestion for me? Is there something missing or a workaround I can use?

Thanks in advance!

__Expected Behavior__

The extensions `dm:priority` and `dm:category` should have been removed.

__Note__
This issue is the same of #888 which has been closed a short time ago with #1137. However, updating bpmn-js to @5.0.4 does not solve this problem.

**Comment by pinussilvestrus** [comment] 2019-09-06 06:36
Hi @Carbammato,

can you maybe post your moddle extension for your custom properties so we that we can easier debugging it?

**Comment by philippfromme** [comment] 2019-09-06 06:40
@Carbammato  It looks like tried to attach a screenshot but it didn't work. Can you attach it?

**Comment by philippfromme** [comment] 2019-09-06 06:44
In general, extension elements are copied by default. You can prevent this by hooking into the event bus and applying your own logic:

```javascript
eventBus.on('moddleCopy.canCopyProperty', (context) => {
  const { parent, property, propertyName } = context;
  
  // apply your own logic

  // return false to disallow copying
  return false;
});
```

**Comment by Carbammato** [comment] 2019-09-06 06:45
Hi @pinussilvestrus. Here is an extract of the moddle with the properties interested.

```
{
  "name": "DMCustomi",
  "uri": "http://dm.com/schema/bpmn/nu",
  "prefix": "dm",
  "xml": {
    "tagAlias": "lowerCase"
  },
  "enumerations": [],
  "associations": [],
  "types": [
    {
      "name": "CategoryExtension",
      "superClass": [
        "Element"
      ],
      "properties": [
        {
          "name": "code",
          "isAttr": true,
          "type": "string"
        }
      ]
    },
    {
	"name": "PriorityExtension",
	"superClass": [
	  "Element"
	],
	"properties": [
	  {
	    "name": "code",
	    "isAttr": true,
	    "type": "string"
	  }
	]
     }
  ]
}
```

**Comment by Carbammato** [comment] 2019-09-06 06:52
Hi @philippfromme! I pasted most of that post from this post on the bpmn forum that I opened last year: https://forum.bpmn.io/t/how-to-clear-extensions-when-i-change-task-type/2748/3 .

I'll try to manage the eventBus in order to avoid extensions copy. I actually need that because we're creating several custom properties that might be available based on the task type. Therefore, I'd prefere to avoid any cloning by default. Thank you again!

**Comment by philippfromme** [comment] 2019-09-06 06:54
@Carbammato Nice! We're doing the same with our [camunda-bpmn-moddle extension](https://github.com/camunda/camunda-bpmn-moddle/blob/master/lib/extension.js#L14). 💪

**Comment by philippfromme** [comment] 2019-09-06 06:54
Can we close this as it is not a bug?

**Comment by pinussilvestrus** [comment] 2019-09-06 06:56
Yes.

**Closed by pinussilvestrus** 2019-09-06 06:56 UTC
Labels: help wanted

**Comment by Carbammato** [comment] 2019-09-06 09:00
@philippfromme sorry to bother you again, but it seems the event doesn't trigger. I try to create the event in my BpmnPropertiesProvider, just after creating the tabs, but the Chrome Debugger doesn't notice any evaluation of the code when the event trigger. I'm trying to debug a little and I noticed that the `copyProperty` function inside `Moddle.copy.js` is called from `BpmnReplace.js`, but also I can't understand when this other function get called.

**Comment by philippfromme** [comment] 2019-09-06 09:02
The event is fired when `ModdleCopy#copyElement` is used (copy & paste, replace). When are you expecting the event to be fired?

**Comment by Carbammato** [comment] 2019-09-06 09:11
@philippfrommeI basically need an event whenever I change the task type. Something like an update, because of this I thought that "replace" could be a good solution. What kind of event I might need when I simply change the task type?

**Comment by nikku** [comment] 2019-09-06 09:19
@Carbammato When replacing tasks we copy across all compatible properties. The events shared allow you to fine tune what is being copied across.

As mentioned by @philippfromme [camunda-bpmn-moddle](https://github.com/camunda/camunda-bpmn-moddle) [does exactly what you need](https://github.com/camunda/camunda-bpmn-moddle#bpmn-js-extension): It hooks into the replace events and ensures that only compatible extension properties are carried over when replacing one task type with another.

I think at this point it makes sense if you share a full example of what you're doing and link the place that is blocking you.

**Comment by Carbammato** [comment] 2019-09-06 09:54
I apologize, guys. It's my fault. the solution proposed by @philippfromme works exactly as it should. Somehow I didn't notice that the event was hooked and deleting extensions as I wanted. 

Sorry again and thank you for your work! ;-)

**Comment by philippfromme** [comment] 2019-09-06 09:58
@Carbammato 💪 👍
