### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by maayanl600** [bpmn-io/bpmn-js#939] opened 2019-02-20 14:27 UTC
__Describe the Bug__

The event “mouse-down” is throwing exception in the method preventDefault in bpmn-modeler.development.js
The exception is:
“Unable to preventDefault inside passive event listener invocation”

I looked for this error online and found the following:
“When using third party libraries (e.g. jQuery or lory.js) this error rises often - it’s due to fact that their listeners arent using passive event flag as default and still use preventDefault which in case of our default-passive property raises an error.”

__Steps to Reproduce__

1. drag two elements to the canvas
2. click on the arrow in the context pad on one element
3. connect this element to the other
4. in Dev-Tool you can see the following error:
![image](https://user-images.githubusercontent.com/24764721/53098335-13e33000-352c-11e9-9b9a-e0551ea03cba.png)

If you report a modeling related issue, ensure you can reproduce it on [demo.bpmn.io](https://demo.bpmn.io/new)

When reporting a library error, try to build an example that reproduces your problem. You can use our playgrounds for [viewer](https://jsfiddle.net/07envcu1/) or [modeler](https://jsfiddle.net/bg97r61t/) as a starting point or put a demo up on [GitHub](https://github.com/) for inspection.

__Expected Behavior__

No error

__Environment__

 - Browser: Chrome 72
 - OS: Windows 10
 - Library version: I have tried on 1.1.1 and also on last version 3.2.1. In both cases the error is reproduced

**Comment by nikku** [comment] 2019-02-20 15:01
Double post of https://forum.bpmn.io/t/unable-to-preventdefault-inside-passive-event-listener-invocation/3157?

**Comment by nikku** [comment] 2019-02-20 15:01
We accept contributions that improve the situation.

**Comment by nikku** [comment] 2019-02-20 15:02
Were you able to reproduce this issue in [on our demo](https://demo.bpmn.io)?

**Comment by maayanl600** [comment] 2019-02-20 17:32
I couldn't reproduce in the demo.
I new here so I posted a topic in addition. one of the posts can be removed if not necessary .

**Comment by nikku** [comment] 2019-02-21 07:52
It is reladed to `zone.js` and the fact that you use BpmnJS in an Angular.io context.

**Comment by nikku** [comment] 2019-02-21 08:04
I'll close this issue as we cannot reproduce it outside an Angular context. 

We are open to contributions that get rid of the warning for Angular developers.

**Closed by nikku** 2019-02-21 08:04 UTC
Labels: pr-welcome
