### ISSUE TITLE
Chrome opened the existing model font is very large, but just move the window back to normal

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/bpmn-js#1533] opened 2021-11-19 10:16 UTC
__Describe the Bug__
Chrome opened the existing model font is very large, but just move the window back to normal

__Steps to Reproduce__

1. Open the project directly in Chrome to preview the existing model, the font becomes very large, and the MAC browser works fine
![image](https://user-images.githubusercontent.com/62740686/142605393-9cebd96d-d98b-4820-82f2-91bc08c7597e.png)

__Expected Behavior__

__Environment__

 - Browser: [e.g. IE 11, Chrome 69] chrome 96
 - OS: [e.g. Windows 7] mac
 - Library version: [e.g. 2.0.0] bpmn js 8.7.3

**Comment by pinussilvestrus** [comment] 2021-11-19 14:04
I can't reproduce that on https://demo.bpmn.io/s/start. Can you share some more details on how to reproduce that behavior?

**Comment by zxiaozhou** [comment] 2021-11-20 19:40
@pinussilvestrus I found that the pop-up mode was used to open the exception，chrome(96),This is the smallest case I have provided(But I'm not sure if it's BPMN JS or my personal reasons or other reasons)
https://github.com/zxiaozhou/minimum-case

**Comment by nikku** [comment] 2021-11-24 12:12
Hi @zxiaozhou! Unfortunately your repository is too big for me to set it up in a [codesandbox](http://codesandbox.io/).

As this seems to be related to whether things are embedded in a model (or not), I'd suggest you to debug the label elements and the computed CSS these are using. Maybe the modal overrides font sizes?

**Comment by nikku** [comment] 2021-11-30 08:53
Closing due to inactivity.

**Comment by zxiaozhou** [comment] 2021-11-30 08:56
@nikku I don't think it's overwritten, because I just move the model and it's back to normal, if it's overwritten, it shouldn't be able to move it back to normal

**Comment by Satsiki** [comment] 2021-12-07 08:33
> @nikku我不认为它被覆盖了，因为我只是移动了模型，它又恢复了正常，如果它被覆盖了，它应该无法将它移回正常

Did you solve it, I also encountered this problem

**Comment by Satsiki** [comment] 2021-12-07 08:33
> @nikku I don't think it's overwritten, because I just move the model and it's back to normal, if it's overwritten, it shouldn't be able to move it back to normal

Did you solve it, I also encountered this problem

**Comment by graceful-qi** [comment] 2021-12-10 09:49
I also found this problem, mainly triggered when the window is opened for the first time. Do you have a solution now?

**Comment by zxiaozhou** [comment] 2021-12-10 19:03
@nikku @Satsiki @graceful-qi I didn't solve it。
@nikku I think it's really arbitrary for you to just say CSS overlay. As of today's test, only Chrome 96 is abnormal, and versions below 96 and the latest 97 beta are normal
<img width="1663" alt="iShot2021-12-11 03 00 11" src="https://user-images.githubusercontent.com/62740686/145627822-c13aa8fa-74ef-4ad3-a5d8-d216a0b62128.png">

**Comment by zxiaozhou** [comment] 2021-12-10 19:07
@graceful-qi @pinussilvestrus @Satsiki 
Chrome 97 beta is normal, or less than 96 is normal, so just wait for chrome to come out with a new version

**Comment by graceful-qi** [comment] 2021-12-14 01:27
@zxiaozhou Thank you for your reply, after I tested it and found it to be true, it looks like I'll have to wait for the chrome update.

**Comment by nikku** [comment] 2021-12-14 07:57
Thanks for root causing this as a Chrome bug. 

In rare cases you see this happening. Closing this issue.

**Closed by nikku** 2021-12-14 07:57 UTC
Labels: bug, help wanted
