### ISSUE TITLE
Selecting an element via TOUCH does not work correctly

### ISSUE THREAD

**Issue by John0x** [bpmn-io/bpmn-js#625] opened 2016-11-04 10:32 UTC
Hey, I've bundeled the bpmn-js modeler (newest version) with bower and integrated it into my ionic 2 (angular 2) app.
It is hard to click on an element because the bounding box does not seem to work. I have to click multiple times to select an element.
Dragging (Holding down over the element) though works fine.

**Comment by nikku** [comment] 2017-12-07 23:35
Thanks for the bug report. Mobile support is not the best right now. At some point we'll revise it.

**Comment by nikku** [comment] 2017-12-07 23:41
Duplicate of https://github.com/bpmn-io/bpmn-js/issues/449.

**Closed by nikku** 2017-12-07 23:41 UTC
Labels: duplicate, mobile
