### ISSUE TITLE
Cannot read property 'bpmnElement' of undefined

### ISSUE THREAD

**Issue by felipebelluco** [bpmn-io/bpmn-js#1145] opened 2019-08-05 19:10 UTC
I'm trying to upload the following file using the function `modeler.importXML` :

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn">
  <bpmn:collaboration id="Collaboration_1fmiwwq">
    <bpmn:participant id="Participant_0lfdojl" processRef="Process_0uzpyqa" />
  </bpmn:collaboration>
  <bpmn:process id="Process_0uzpyqa">
    <bpmn:startEvent id="StartEvent_01fj072" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1fmiwwq">
      <bpmndi:BPMNShape id="Participant_0lfdojl_di" bpmnElement="Participant_0lfdojl">
        <dc:Bounds x="142" y="261" width="600" height="250" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="StartEvent_01fj072_di" bpmnElement="StartEvent_01fj072">
        <dc:Bounds x="211" y="368" width="36" height="36" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

But I'm receiving this error:

`TypeError: Cannot read property 'bpmnElement' of undefined`

The interesting fact about this error is that I'm using a file built with the modeler.

**Comment by nikku** [comment] 2019-08-06 05:49
How do you reproduce the issue? Opening the diagram on [demo.bpmn.io](https://demo.bpmn.io/) works absolutely fine.

**Comment by felipebelluco** [comment] 2019-08-06 13:48
I know, interestingly it works fine when localhost, but when I publish it into a server it doesn't load at all,  and gives that error. I'm using it inside an Angular 7 app; I don't know if it's relevant or not.

**Comment by nikku** [comment] 2019-08-06 13:54
> How do you reproduce the issue?

"I know" is not an appropriate answer to this question :wink:.

We seen a lot of people having issues with using bpmn-js from Angular. The reason is that Angular aggressively optimizes the code, removing critical bits. I suggest you to use the pre-packaged distribution and see if the error vanishes.

I'll close this issue, as we cannot help you without a concrete setup that allows us to reproduce your case.

**Closed by nikku** 2019-08-06 13:54 UTC
Labels: help wanted

**Comment by felipebelluco** [comment] 2019-08-06 14:34
By "I know" I'm agreeing with you when you say it works fine on demo. About the issue, I could give you any kind of necessary info to reproduce the issue if only I knew what you need. Not every user are as expert as you guys! Thanks for the hint, I'll go for it.

**Comment by nikku** [comment] 2019-08-06 16:57
With every non-trivial bug report we need your exact environment and steps that allow us to reproduce the issue. 

We got an issue template for bugs. If you use that next time you open a bug report, you'd be covered in most aspects.

**Comment by Javarome** [comment] 2023-10-21 09:55
@felipebelluco maybe you provided a second argument to `viewer.importXML(xml, something)`? Depending on the viewer you use, this can be an old-fashioned "done" callback (like in the CMMN viewer) or, using the BPMN viewer, an optional 
`bpmnDiagram` instance or id of it so it can be opened. 

So when such a second argument is provided to the BPMN viewer, it will be interpreted as `viewer.importXML(xml, bpmnDiagram)` and at some point it will try to access `bpmnDiagram.plane.bpmnElement`. If the provided argument is not a bpmnDiagram object, it will not likely bear a `plane` property and so this will result in `Cannot read property 'bpmnElement' of undefined`.

**Comment by AngelEscobedoWH** [comment] 2024-04-11 20:08
If anybody else was still having issues with this, I was able to solve it by changing the way I was using the `importXML` function.
The code below is what broke for me. 
```
bpmnViewer.importXML(xml, (err) => {
    if (err) {
        console.error('Error importing XML:', err);
    } else {
        console.log('XML imported successfully!');
    }
});
```

The code below is what worked for me.
```
viewerRef.importXML(xml)
    .then((result) => {
        const { warnings } = result;
        console.log("BPMN diagram loaded successfully!", warnings);
    })
    .catch((err) => {
        const { warnings, message } = err;
        console.log("Something went wrong:", warnings, message);
    });
```

Hope this helps somebody.

**Comment by nikku** [comment] 2024-04-11 20:52
Cf. [`v7.0.0`](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#700) where we introduce the new API and start to warn about callbacks being deprecated. We removed the old callback style API completely with [`v14.0.0`](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#1400).
