### ISSUE TITLE
Scrolling to the Selected Element Doesn't Behave as Expected

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1448] opened 2021-05-10 12:45 UTC
__Describe the Bug__

In some cases, selected elements are always in bottom left 

![Xx3l8Yuu28](https://user-images.githubusercontent.com/7633572/117660352-5e006c80-b19d-11eb-9dee-8916d04f89f6.gif)

__Steps to Reproduce__

1. Model this diagram: https://github.com/camunda/camunda-modeler/blob/master/docs/.project/test.bpmn.png
2. Use search feature to scroll to elements

__Expected Behavior__

Canvas should only scroll to ensure selected element visible.

__Environment__

 - Library version: 8.5.0

Diagram:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_0fa5dbx" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="4.8.1" modeler:executionPlatform="Camunda Platform" modeler:executionPlatformVersion="7.15.0">
  <bpmn:collaboration id="Collaboration_1g1tpyn">
    <bpmn:participant id="Participant_1x1wbl1" processRef="Process_0d3rg3w" />
    <bpmn:participant id="Participant_0tjqknz" name="Foo1" />
    <bpmn:participant id="Participant_0ld0ljt" processRef="Process_12qisua" />
    <bpmn:messageFlow id="Flow_0yj0bpn" sourceRef="Participant_0tjqknz" targetRef="StartEvent_1" />
    <bpmn:messageFlow id="Flow_1igakg9" sourceRef="Event_0ve6ova" targetRef="Event_0fcdnvc" />
  </bpmn:collaboration>
  <bpmn:process id="Process_0d3rg3w" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_0ewmewl</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:endEvent id="Event_0ve6ova" name="Foo5">
      <bpmn:incoming>Flow_153n2db</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:dataStoreReference id="DataStoreReference_13cpr4f" name="Foo4" />
    <bpmn:subProcess id="Activity_14gu7x5">
      <bpmn:incoming>Flow_0ewmewl</bpmn:incoming>
      <bpmn:outgoing>Flow_153n2db</bpmn:outgoing>
      <bpmn:multiInstanceLoopCharacteristics />
      <bpmn:task id="Activity_1v6fip6" name="Foo2">
        <bpmn:outgoing>Flow_0vxnp2r</bpmn:outgoing>
      </bpmn:task>
      <bpmn:task id="Activity_0h6e2kb" name="Foo3">
        <bpmn:incoming>Flow_0vxnp2r</bpmn:incoming>
        <bpmn:dataOutputAssociation id="DataOutputAssociation_1bz29g6">
          <bpmn:targetRef>DataStoreReference_13cpr4f</bpmn:targetRef>
        </bpmn:dataOutputAssociation>
      </bpmn:task>
      <bpmn:sequenceFlow id="Flow_0vxnp2r" sourceRef="Activity_1v6fip6" targetRef="Activity_0h6e2kb" />
    </bpmn:subProcess>
    <bpmn:sequenceFlow id="Flow_0ewmewl" sourceRef="StartEvent_1" targetRef="Activity_14gu7x5" />
    <bpmn:sequenceFlow id="Flow_153n2db" sourceRef="Activity_14gu7x5" targetRef="Event_0ve6ova" />
    <bpmn:textAnnotation id="TextAnnotation_000uus5" />
    <bpmn:association id="Association_075qxti" sourceRef="Activity_14gu7x5" targetRef="TextAnnotation_000uus5" />
  </bpmn:process>
  <bpmn:process id="Process_12qisua" isExecutable="false">
    <bpmn:startEvent id="Event_0fcdnvc">
      <bpmn:outgoing>Flow_0jsvuzt</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:exclusiveGateway id="Gateway_1uivwfm">
      <bpmn:incoming>Flow_0jsvuzt</bpmn:incoming>
      <bpmn:outgoing>Flow_1wcif9f</bpmn:outgoing>
      <bpmn:outgoing>Flow_0qzxnjw</bpmn:outgoing>
    </bpmn:exclusiveGateway>
    <bpmn:task id="Activity_03bt7t0">
      <bpmn:incoming>Flow_1wcif9f</bpmn:incoming>
      <bpmn:outgoing>Flow_0gxdwoh</bpmn:outgoing>
    </bpmn:task>
    <bpmn:endEvent id="Event_099nugo">
      <bpmn:incoming>Flow_0gxdwoh</bpmn:incoming>
      <bpmn:incoming>Flow_0qzxnjw</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_0jsvuzt" sourceRef="Event_0fcdnvc" targetRef="Gateway_1uivwfm" />
    <bpmn:sequenceFlow id="Flow_1wcif9f" sourceRef="Gateway_1uivwfm" targetRef="Activity_03bt7t0" />
    <bpmn:sequenceFlow id="Flow_0gxdwoh" sourceRef="Activity_03bt7t0" targetRef="Event_099nugo" />
    <bpmn:sequenceFlow id="Flow_0qzxnjw" sourceRef="Gateway_1uivwfm" targetRef="Event_099nugo" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Collaboration_1g1tpyn">
      <bpmndi:BPMNShape id="Participant_1x1wbl1_di" bpmnElement="Participant_1x1wbl1" isHorizontal="true">
        <dc:Bounds x="129" y="80" width="600" height="460" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="TextAnnotation_000uus5_di" bpmnElement="TextAnnotation_000uus5">
        <dc:Bounds x="610" y="140" width="100" height="30" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0ewmewl_di" bpmnElement="Flow_0ewmewl">
        <di:waypoint x="215" y="327" />
        <di:waypoint x="260" y="327" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_153n2db_di" bpmnElement="Flow_153n2db">
        <di:waypoint x="610" y="327" />
        <di:waypoint x="662" y="327" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="309" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_0ve6ova_di" bpmnElement="Event_0ve6ova">
        <dc:Bounds x="662" y="309" width="36" height="36" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="667" y="279" width="26" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="DataStoreReference_13cpr4f_di" bpmnElement="DataStoreReference_13cpr4f">
        <dc:Bounds x="485" y="455" width="50" height="50" />
        <bpmndi:BPMNLabel>
          <dc:Bounds x="497" y="512" width="26" height="14" />
        </bpmndi:BPMNLabel>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_14gu7x5_di" bpmnElement="Activity_14gu7x5" isExpanded="true">
        <dc:Bounds x="260" y="227" width="350" height="200" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0vxnp2r_di" bpmnElement="Flow_0vxnp2r">
        <di:waypoint x="410" y="330" />
        <di:waypoint x="460" y="330" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Activity_1v6fip6_di" bpmnElement="Activity_1v6fip6">
        <dc:Bounds x="310" y="290" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0h6e2kb_di" bpmnElement="Activity_0h6e2kb">
        <dc:Bounds x="460" y="290" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Association_075qxti_di" bpmnElement="Association_075qxti">
        <di:waypoint x="566" y="227" />
        <di:waypoint x="640" y="170" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Participant_0di2ux9_di" bpmnElement="Participant_0tjqknz" isHorizontal="true">
        <dc:Bounds x="129" y="560" width="301" height="60" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Participant_0ld0ljt_di" bpmnElement="Participant_0ld0ljt" isHorizontal="true">
        <dc:Bounds x="129" y="690" width="600" height="250" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_0jsvuzt_di" bpmnElement="Flow_0jsvuzt">
        <di:waypoint x="238" y="820" />
        <di:waypoint x="295" y="820" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1wcif9f_di" bpmnElement="Flow_1wcif9f">
        <di:waypoint x="345" y="820" />
        <di:waypoint x="410" y="820" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0gxdwoh_di" bpmnElement="Flow_0gxdwoh">
        <di:waypoint x="510" y="820" />
        <di:waypoint x="582" y="820" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0qzxnjw_di" bpmnElement="Flow_0qzxnjw">
        <di:waypoint x="320" y="795" />
        <di:waypoint x="320" y="740" />
        <di:waypoint x="600" y="740" />
        <di:waypoint x="600" y="802" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="Event_0fcdnvc_di" bpmnElement="Event_0fcdnvc">
        <dc:Bounds x="202" y="802" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Gateway_1uivwfm_di" bpmnElement="Gateway_1uivwfm" isMarkerVisible="true">
        <dc:Bounds x="295" y="795" width="50" height="50" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_03bt7t0_di" bpmnElement="Activity_03bt7t0">
        <dc:Bounds x="410" y="780" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_099nugo_di" bpmnElement="Event_099nugo">
        <dc:Bounds x="582" y="802" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="DataOutputAssociation_1bz29g6_di" bpmnElement="DataOutputAssociation_1bz29g6">
        <di:waypoint x="510" y="370" />
        <di:waypoint x="510" y="455" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_0yj0bpn_di" bpmnElement="Flow_0yj0bpn">
        <di:waypoint x="197" y="560" />
        <di:waypoint x="197" y="345" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_1igakg9_di" bpmnElement="Flow_1igakg9">
        <di:waypoint x="680" y="345" />
        <di:waypoint x="680" y="660" />
        <di:waypoint x="220" y="660" />
        <di:waypoint x="220" y="802" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by nikku** [comment] 2021-05-17 09:03
For convenience, could you attach the modeled diagram? That would help a lot to reproduce the issue.

**Comment by nikku** [comment] 2021-05-17 09:04
I believe @marstamm could then have a quick look at it and see what is missing with the new scroll-to-element behavior.

**Comment by philippfromme** [comment] 2021-05-17 10:56
Done.

**Comment by marstamm** [comment] 2021-05-17 11:21
*Root cause*
When using the search box, we apply [generous padding](https://github.com/bpmn-io/diagram-js/blob/develop/lib/features/search-pad/SearchPad.js#L390) to the viewbox (400 top, 100 bottom). 
When in a small window and zoomed in, many elements will not fit the remaining height. We decided that we should focus on the top-left element in case a element does not fit. In that sense, it would be "expected behavior" 

*Possible Solutions*
- Shrink padding (does not really solve the issue, but makes it less common)
- Add specialized behavior for cases where one dimension fits, but not the other
- Do nothing as it works in big windows/Fullscreen with sensible zoom-levels and the element is still visible

**Comment by philippfromme** [comment] 2021-05-17 11:37
Okay, if this is the expected behavior I'm fine with leaving it as it is. 👍🏻

**Comment by nikku** [comment] 2021-05-17 11:56
Thanks folks!

Based on the exchange I'm closing as won't fix. 

If we receive this feedback more often we can decide to put more effort into further improvements.

**Closed by nikku** 2021-05-17 11:56 UTC
Labels: bug
