### ISSUE TITLE
request for vertical lane support

### ISSUE THREAD

**Issue by mandrakeli** [bpmn-io/bpmn-js#1482] opened 2021-09-07 06:08 UTC
__Is your feature request related to a problem? Please describe.__

when i create a bpmn xml with vertical lane，i found the lane.name is layout on the left not on the top，please correct or support it with right place，thx！

__Describe the solution you'd like__

vertical lane's layout on the top

__Describe alternatives you've considered__

..

__Additional context__

![image](https://user-images.githubusercontent.com/1314462/132292576-0d5952f6-5dfa-4339-8962-96ec73e8e8c8.png)

[2hlane&2vlane.txt](https://github.com/bpmn-io/bpmn-js/files/7119276/2hlane.2vlane.txt)

**Comment by barmac** [comment] 2021-09-07 06:25
Duplicate of https://github.com/bpmn-io/bpmn-js/issues/507

We are open to contributions but vertical lanes are not on our roadmap.

**Closed by barmac** 2021-09-07 06:25 UTC
Labels: enhancement
