### ISSUE TITLE
Text annotation connection i not correctly displayed/attached when outside element bounding box

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/bpmn-js#515] opened 2016-04-22 08:08 UTC
Attach annotation to interaction rect but outside text annotation bounding box:

![label-1](https://cloud.githubusercontent.com/assets/2331533/14735380/db65e3fc-0870-11e6-81f3-a89daca98678.gif)

**Note:** It works fine when attachning the annotation to the elements bounding box (see below).

![text-annotation](https://cloud.githubusercontent.com/assets/58601/14949006/72d9d34c-1046-11e6-88df-f848101fc1f6.gif)

**Comment by philippfromme** [comment] 2019-11-15 13:40
Cannot reproduce anymore. Closing.

**Closed by philippfromme** 2019-11-15 13:40 UTC
Labels: backlog, bug, modeling
