### ISSUE TITLE
Support BPMN Data Input/Output and Collection elements

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js#1323] opened 2020-05-05 22:02 UTC

**Comment by pinussilvestrus** [comment] 2020-05-06 10:57
Is this a duplicate of https://github.com/bpmn-io/bpmn-js/issues/951?

**Comment by falko** [comment] 2020-05-06 11:43
Almost. This one also adds the collection marker.

Sent from mobile device.

________________________________

**Comment by nikku** [comment] 2020-05-06 11:46
Regarding the collection markers, is this covered by https://github.com/bpmn-io/bpmn-js/issues/381?

**Comment by falko** [comment] 2020-05-06 13:50
Yes if that adds them to Data Inputs and Outputs es well.

**Comment by falko** [comment] 2020-05-06 13:50
Yes if that adds them to Data Inputs and Outputs as well.

**Comment by nikku** [comment] 2020-05-07 08:14
Closing this as a duplicate of https://github.com/bpmn-io/bpmn-js/issues/381 and https://github.com/bpmn-io/bpmn-js/issues/951.

**Closed by nikku** 2020-05-07 08:14 UTC
Labels: enhancement
