### ISSUE TITLE
Modeling unusable in Safari

### ISSUE THREAD

**Issue by benhoffmann** [bpmn-io/bpmn-js#1598] opened 2022-02-11 12:24 UTC
__Describe the Bug__

bpmn.io seems to be unusable in Safari 15.2
I suspect that it broke with some version update.

Cawemo works
bpmn.io demo and Console Modeler doesnt work

__Steps to Reproduce__

![bpmn-io](https://user-images.githubusercontent.com/17595149/153590936-39cc7064-80ae-4657-8d07-43e512f5a3ee.gif)
![cawemo](https://user-images.githubusercontent.com/17595149/153590945-88dbbbe0-55b7-4d22-b0a2-b9763de9369c.gif)
![cloud](https://user-images.githubusercontent.com/17595149/153590950-17952d44-9599-41f0-bdbd-6d644ba8f04d.gif)

__Expected Behavior__

Although Safari is not fully supported, ensure at least basic functionality

__Environment__

 - Browser: Safari 15.2
 - OS: MacOS 12.1
 - Library version: don't know

**Comment by barmac** [comment] 2022-02-11 13:03
Thanks for reporting. I cannot reproduce it in version 14.1.1 (16611.2.7.1.4) but will upgrade and check again.

**Comment by barmac** [comment] 2022-02-11 14:36
I've just upgraded MacOS to 12.2.1 and it comes with Safari 15.3. Fortunately, demo.bpmn.io works correctly with that version of the browser so I'd suggest to update. However, this means that I need to close this issue as we don't support specific outdated versions of any browser.

**Closed as completed by barmac** 2022-02-11 14:36 UTC
Labels: bug, browser:Webkit, wontfix

**Comment by benhoffmann** [comment] 2022-02-17 07:40
Hi @barmac , I can confirm that demo.bpmn.io works correctly with the latest version of Safari.

The Cloud Console Modeler still doesn't work, but I found the issue https://github.com/camunda/web-modeler/issues/349 which is already addressing. Just adding this for context.

**Comment by barmac** [comment] 2022-02-17 08:07
Hi @benhoffmann, thanks for getting back to me. I am happy that the issue on the demo website is resolved for you. Thanks for notice on the web modeler.

**Comment by CatalinaMoisuc** [comment] 2022-02-17 10:59
Hi @benhoffmann see the latest update on https://github.com/camunda/web-modeler/issues/349#issuecomment-1042770322.
