### ISSUE TITLE
Connecting a Task from a different Pool/process very difficult

### ISSUE THREAD

**Issue by mitchhanks** [bpmn-io/bpmn-js#1075] opened 2019-06-12 16:58 UTC
__Describe the Bug__

The X position seems to be way off when connecting a task from another process/pool.

__Steps to Reproduce__

1. Have a diagram with multiple processes
2. Try to connect a task from one process to another in a different process

Video of the issue:
https://www.screencast.com/t/B4kNQG7VBA

If you report a modeling related issue, ensure you can reproduce it on [demo.bpmn.io](https://demo.bpmn.io/new)

__Expected Behavior__

Create a bpmn2:incoming/outgoing to and from the two tasks with no issue.

__Environment__

Please complete the following information:

 - Browser:  Chrome 75
 - OS: Windows 10 pro
 - Library version: bpmn-js - bpmn-modeler v3.4.1

**Comment by nikku** [comment] 2019-06-13 10:29
Unfortunately I do not have flash (and thus, cannot watch your screencast). Could you share a link to a video or GIF recording?

**Comment by mitchhanks** [comment] 2019-06-13 10:43
![bpmnError](https://user-images.githubusercontent.com/22320309/59426577-6a70c480-8dd0-11e9-91e9-e295a2c285fa.gif)
Here you go :)

**Comment by nikku** [comment] 2019-06-13 11:28
What you show looks like very odd behavior.

Could you verify whether you can still reproduce this issue in [our demo](https://demo.bpmn.io/s/start). It contains the soon to be release version `v4.0.0` of bpmn-js, adding substantial improvements to the overall modeling experience, including connection layouting.

If you can still reproduce it:

* provide us with a minimal test diagram to start with
* provide us with a minimal screen cast that showcases the bug (using our demo)

This way we have a great foundation to look into this issue and improve things.

**Comment by mitchhanks** [comment] 2019-06-17 07:46
Hi Nikku,

I tried to reproduce the issue in the link and everything is working as expected :) 

Hopefully version 4 fixes the issue and it;s not something weird on our end locally.

Is there any ETA on version 4?

Thanks, Mitch

**Comment by nikku** [comment] 2019-06-17 07:48
Closing this as a duplicate of https://github.com/bpmn-io/bpmn-js/issues/950 then.

Thanks for the heads up!

**Closed by nikku** 2019-06-17 07:48 UTC
