### ISSUE TITLE
unparsable content </bpmn:task> detected; this may indicate an invalid BPMN 2.0 diagram file

### ISSUE THREAD

**Issue by egorTriceps** [bpmn-io/bpmn-js#1907] opened 2023-05-12 09:09 UTC
### Describe the Bug

```xml
unparsable content </bpmn:task> detected; this may indicate an invalid BPMN 2.0 diagram file
	line: 46
	column: 6
	nested error: closing tag mismatch
```

when opening the file, it gives this error

### Environment

 - Browser: [ Chrome 69]
 - OS: [ Windows 10]

**Comment by nikku** [comment] 2023-05-12 12:07
@egorTriceps I have a number of questions:

* How did this error happen?
* What is the diagram that triggers this error?
* How can we help yoU?

**Comment by egorTriceps** [comment] 2023-05-12 14:25
[Заявка на потребность.zip](https://github.com/bpmn-io/bpmn-js/files/11465026/default.zip)
in each line where "name =" is written, incomprehensible characters are written

**Comment by nikku** [comment] 2023-05-15 06:21
How can we reproduce your issue? Do you create this broken diagram using our tooling (i.e. https://demo.bpmn.io?

**Comment by egorTriceps** [comment] 2023-05-17 11:16
@nikku Yes

**Comment by egorTriceps** [comment] 2023-05-17 11:17
I saved the file through the demo version of the site, after that I could not upload this file to the site

**Comment by nikku** [comment] 2023-05-17 11:18
We need concrete steps to reproduce. So if you'd try again, on a small file, to reproduce the issue and report back what you found, that would be amazing.

We'll otherwise not be able to help you.

**Comment by barmac** [comment] 2023-05-17 12:08
I tried Russian keyboard on my Mac but couldn't reproduce the issue.

**Comment by egorTriceps** [comment] 2023-05-18 06:34
How can I restore the table?

**Comment by barmac** [comment] 2023-05-18 10:45
Perhaps this helps: https://stackoverflow.com/questions/43108359/how-to-remove-all-special-characters-in-linux-text

I am closing this issue as we cannot reproduce the problem.

**Closed by barmac** 2023-05-18 10:45 UTC
Labels: bug, needs more information
