### ISSUE TITLE
Expanding subprocess without space messes up model

### ISSUE THREAD

**Issue by rajgoel** [bpmn-io/bpmn-js#1868] opened 2023-03-13 17:46 UTC
### Describe the Bug

Expanding a collapsed subprocess may create a mess with overlapping nodes if there is no space. Also the layering of nodes and sequence flows appears to be messed up.

### Steps to Reproduce

1. Create a model in demo.bpmn.io with a collapsed subprocess that is larger than the space available in the parent
2. Expand the subprocess

![ExpandSubprocess](https://user-images.githubusercontent.com/4448455/224784746-765eefd6-fd82-4ddd-902b-4f2fe6472260.gif)

Related to: https://github.com/marstamm/bpmn-js-move-to-subprocess/issues/1

### Expected Behavior

Ideally, the modeller would automatically create space before expanding the collapsed subprocess.

Currently, the user must use the create space tool before expanding the collapsed subprocess.

### Environment

 - Browser: FF110
 - OS: Ubuntu 18.04
 - Library version: demo.bpmn.io

**Comment by rajgoel** [comment] 2023-03-14 08:36
Here's another example produced with the demo:

![ExpandSubprocess2](https://user-images.githubusercontent.com/4448455/224942444-a747c55f-5ae2-4bca-a999-a1d374795f96.gif)

The original start node is hidden behind the subprocess, but the sequence flow stays on top.

**Comment by barmac** [comment] 2023-03-21 09:51
This is a duplicate of https://github.com/bpmn-io/bpmn-js/issues/1102

Do you have any suggestions how we could solve the problem? Please share them in the linked issue.

**Closed by barmac** 2023-03-21 09:51 UTC
Labels: bug
