### ISSUE TITLE
 The New popup menu UI is not displayed in full screen

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/bpmn-js#1795] opened 2022-12-19 10:04 UTC
__Describe the Bug__

 The New popup menu UI is not displayed in full screen

1. not full
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/62740686/208399797-a90f4f1d-ee9d-4dfd-8888-5ed7df5802fd.png">
2. full 
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/62740686/208399545-83327aee-62fe-414d-b3ec-5511e3d699bd.png">

__Steps to Reproduce__

1.  Set browser content to full screen
3. clieck change type icon
4. popup menu not displayed

__Expected Behavior__

__Environment__

 - Browser: [e.g. IE 11, Chrome 69] 108
 - OS: [e.g. Windows 7] mac
 - Library version: [e.g. 2.0.0] bpmn js 11.1.0

**Comment by nikku** [comment] 2022-12-19 10:31
I can reproduce it:

```
const container = document.querySelector('bjs-container');
container.requestFullscreen();
```

The issue is that the popup menu now lives outside the diagram canvas, a behavior we'd need to revise if we wanted to fix this.

CC @smbea.

**Comment by nikku** [comment] 2023-01-01 22:06
Reproduce using our test suite (`npm start`) and [these steps](https://github.com/bpmn-io/bpmn-js/issues/1795#issuecomment-1357432582).

![capture ihIbDA_optimized](https://user-images.githubusercontent.com/58601/210185949-2b7cb441-87fc-4666-97b9-45aed74f585a.gif)

**Comment by nikku** [comment] 2023-01-06 14:07
Closed via https://github.com/bpmn-io/bpmn-js/commit/ca4559fa7317ebdb21c243e2f757c3631fc5370e.

**Closed by nikku** 2023-01-06 14:07 UTC
Labels: bug, fixed upstream
