### ISSUE TITLE
Create connector from Boundary event to element makes unnecessary bend point

### ISSUE THREAD

**Issue by ignacio-ac14** [bpmn-io/bpmn-js#891] opened 2018-10-30 18:56 UTC
__Describe the Bug__

When you create a connection from a boundary event to any other element, that it's aligned to the boundary, the connector has a new bend point in the center of the target element and the connector's end is in the in the middle of the side.
The bug occurs when the connector should be just straight

__Steps to Reproduce__

![2018-10-30_15-38-12](https://user-images.githubusercontent.com/13072874/47743646-4ce65480-dc5e-11e8-819d-a885bc82f19a.gif)

__Expected Behavior__

The connector should be a straight line.

__Environment__

 - Browser: Chrome 69
 - OS: Windows 10
 - Library version: 2.5.2

**Comment by pinussilvestrus** [comment] 2018-10-31 08:09
Hi @ignacio-ac14 thanks for reporting! 

I can reproduce it on https://demo.bpmn.io/new.

![okt -31-2018 09-08-18](https://user-images.githubusercontent.com/9433996/47774205-9e3d2500-dcec-11e8-81ed-392d4597062f.gif)

**Comment by nikku** [comment] 2019-03-06 10:39
This has been reported on multiple occasions and seems to be a duplicate / related to https://github.com/bpmn-io/bpmn-js/issues/891.

**Comment by barmac** [comment] 2019-04-23 09:57
Notes for myself:

It seems like the BpmnLayouter enforces a wrong layout for a boundary event in this line: https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/BpmnLayouter.js#L89
I got `[ 't:h' ]` for a situation when `[ 't:b' ]` is the reasonable layout.

**Comment by nikku** [comment] 2019-04-24 11:56
Closed via https://github.com/bpmn-io/bpmn-js/pull/994.

**Closed by nikku** 2019-04-24 11:56 UTC
Labels: bug, modeling, needs review
