### ISSUE TITLE
Connection tool the diagram preview is cut of somewhere.

### ISSUE THREAD

**Issue by xachary** [bpmn-io/bpmn-js#1370] opened 2020-11-16 00:52 UTC
__Describe the Bug__

Connection tool is missing in somewhere when drawing the line.

__Steps to Reproduce__

* Open [https://demo.bpmn.io/s/start](https://demo.bpmn.io/s/start)
* Move canvas to bottom right by a few pixels
* Activate the connection tool and move over the diagrams `0,0` coordinate origin
* __See that the diagram preview is cut of__

Like this:
[![DPSFPO.gif](https://s3.ax1x.com/2020/11/14/DPSFPO.gif)](https://imgchr.com/i/DPSFPO)

__Expected Behavior__

Preview the connection is correcttly.

__Environment__

 - Browser: IE 11, Chrome 69, Chrome 86, Firefox 82
 - OS: Windows 7, Arch Linux
 - Library version: v7.4.0

**Comment by nikku** [comment] 2020-11-16 06:28
Duplicate of https://github.com/bpmn-io/bpmn-js/issues/1368.

**Closed by nikku** 2020-11-16 06:28 UTC
Labels: bug
