### ISSUE TITLE
Exclusive Gateway Rendering without marker

### ISSUE THREAD

**Issue by sombrek** [bpmn-io/bpmn-js#2063] opened 2023-12-20 15:14 UTC
### Is your feature request related to a problem? Please describe.

BPMN allows displaying exclusive gateways with or without an X shaped marker. This can be controlled using the `isMarkerVisible` attribute. However, the marker is always displayed, ignoring the presence (or absence) of the `isMarkerVisible` attribute.

Some modelers prefer to model without a marker, which is possible in other tools. Modelers ask why this isn't supported, readers who are used to the other style ask what the (missing) X means.

<details>
  <summary>Sample model</summary>

[isMarkerVisible.txt](https://github.com/bpmn-io/bpmn-js/files/13729033/isMarkerVisible.txt)
![sample](https://github.com/bpmn-io/bpmn-js/assets/150448993/46d7b441-6023-4771-a5c7-1045c33d4d44)

</details>

### Describe the solution you'd like

Display the X marker when the `isMarkerVisible` attribute is set to true.
Hide the X marker when the `isMarkerVisible` attribute is either missing or set to false.

<details>
  <summary>Specification excerpts</summary>

![bpmn202p289](https://github.com/bpmn-io/bpmn-js/assets/150448993/ec0d8c4a-9287-4c3f-bcf3-9cc1853efe96)
![bpmn202p400](https://github.com/bpmn-io/bpmn-js/assets/150448993/396fef14-271a-48cf-9d86-4d77192244ae)

</details>

### Describe alternatives you've considered

You could display the marker even when the `isMarkerVisible` attribute is missing.
Pro: Activiti compatibility? See https://forum.bpmn.io/t/when-trying-to-view-a-bpmn-diagram-generated-using-activiti-6-0-0-beta1-the-bpmn-js-viewer-does-not-show-the-exclusive-gateways-as-expected-x/2486
Con: Divergence from the specification.

### Additional context

Possibly #221

In addition to the forum post above, there is another one indicating that this was once supported: https://forum.bpmn.io/t/x-symbol-for-xor-gateway-in-viewer/2342

**Comment by nikku** [comment] 2023-12-20 16:19
I can reproduce your issue. Despite [dedicated handling for it](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/draw/BpmnRenderer.js#L1582) the marker is always shown.

I presume this is due to a bug in [our model import](https://github.com/bpmn-io/bpmn-moddle).

**Comment by nikku** [comment] 2023-12-20 16:20
Changing this to a bug report, as it is against the intended, and implemented behavior.

**Comment by nikku** [comment] 2023-12-20 16:42
> I presume this is due to a bug in [our model import](https://github.com/bpmn-io/bpmn-moddle).

Never mind this. We actually (unnecessarily) [force `isMarkerVisible=true` during modeling](https://github.com/search?q=repo%3Abpmn-io%2Fbpmn-js%20isMarkerVisible&type=code).

**Comment by sombrek** [comment] 2024-01-25 19:10
@barmac Today I noticed that this doesn't work in the latest release, even though my contribution is included. Seems we both forgot to check the diagram after the final changes.

It looks like the simplification is the cause of this, see https://github.com/bpmn-io/bpmn-js/blob/f991d4e08aec1a63575e22a2da1e15e6caa219a3/lib/features/modeling/ElementFactory.js#L221-L223

The original code makes rendering work.
```
    } else {
      attrs = applyAttribute(di, attrs, 'isMarkerVisible');
      if (di.isMarkerVisible === undefined) {
        di.isMarkerVisible = true;
      }
    }
```

What is the best way forward to fix this?

**Comment by barmac** [comment] 2024-01-29 16:19
Thanks for sharing, I will look into this.

**Comment by barmac** [comment] 2024-01-29 16:26
Does it really not work though? I experimented with the following context pad code:

```javascript
        'append.gateway': appendAction(
          'bpmn:ExclusiveGateway',
          'bpmn-icon-gateway-none',
          translate('Append gateway')
        ),
        'append.gateway1': appendAction(
          'bpmn:ExclusiveGateway',
          'bpmn-icon-gateway-none',
          translate('Append gateway'),
          { isMarkerVisible: undefined }
        ),
```

which allowed to create both types of gateway:

https://github.com/bpmn-io/bpmn-js/assets/28307541/827ae95a-ffc6-4156-9501-c62532c33b71

**Comment by sombrek** [comment] 2024-01-30 16:33
@barmac Thanks for getting back to this.

My expectation is that the marker is hidden for existing gateways that have `isMarkerVisible=false`. This doesn't work when I open an existing model, see [test/fixtures/bpmn/draw/xor.bpmn](https://github.com/bpmn-io/bpmn-js/blob/develop/test/fixtures/bpmn/draw/xor.bpmn) in bpmn.io

I guess the same will happen to your model once you save and re-open it.

**Comment by barmac** [comment] 2024-01-30 17:34
OK I can reproduce it with the current version of bpmn-js.

**Comment by barmac** [comment] 2024-01-30 17:47
> I guess the same will happen to your model once you save and re-open it.

So the `isMarkerVisible` is overridden once the XML is exported.

**Comment by barmac** [comment] 2024-02-15 08:39
Closed via https://github.com/bpmn-io/bpmn-js/pull/2102

**Closed by barmac** 2024-02-15 08:39 UTC
Labels: bug, pr welcome, spring cleaning
