### ISSUE TITLE
Error when copy Pool

### ISSUE THREAD

**Issue by hungdaica77** [bpmn-io/bpmn-js#1555] opened 2021-12-23 10:34 UTC
__Describe the Bug__

Duplicate Pool id when copy Pool

__Expected Behavior__

1. Create Pool with Task inside Pool
2. Copy Pool and paste
3. Export
4. Import file was exported

![fail](https://user-images.githubusercontent.com/15230555/147228024-18c202f6-9b3f-4128-8469-1ce583273a3c.gif)

```xml
<bpmn:process id="Process_17iojvx" isExecutable="false">
    <bpmn:task id="Activity_0mkgwx2" />
  </bpmn:process>
  <bpmn:process id="Process_17iojvx" isExecutable="false">
    <bpmn:task id="Activity_1xz8h8p" />
</bpmn:process>
```

__Environment__

 - Browser: [Chrome]
 - OS: [Windows 10]

**Comment by MaxTru** [comment] 2022-01-03 09:56
I cannot reproduce this using 
https://demo.bpmn.io/new

See recording:
![duplicatePoolAndSave](https://user-images.githubusercontent.com/42800119/147917961-2604acc2-17b4-4af4-8080-a9016dacf20c.gif)

Can you please give more detailled steps to reproduce this?

**Comment by hungdaica77** [comment] 2022-01-05 03:08
> I cannot reproduce this using https://demo.bpmn.io/new
> 
> See recording: ![duplicatePoolAndSave](https://user-images.githubusercontent.com/42800119/147917961-2604acc2-17b4-4af4-8080-a9016dacf20c.gif)
> 
> Can you please give more detailled steps to reproduce this?

After export. You need import file was exported.

**Comment by MaxTru** [comment] 2022-01-05 11:47
Ah got it - thanks. I can reproduce this. We will have a look.

**Comment by marstamm** [comment] 2022-01-17 15:13
**Root Cause**

When morphing the Process into a Collaboration, the ID get's unclaimed.
https://github.com/bpmn-io/bpmn-js/blob/fe11c2ee78000449ba20412c99be30be95bf776d/lib/features/modeling/behavior/UnclaimIdBehavior.js#L50

With https://github.com/camunda/camunda-modeler/issues/1410, we keep the IDs when copying Elements, so we create the process with the same ID again.

**Solution Sketch**
Determine if it makes sense to unclaim IDs when the root changes but nothing is deleted and either:
- Remove the code that unclaims the ID
- Ensure the ID is re-claimed once the new participant with a `processRef`is created

**Comment by MaxTru** [comment] 2022-01-19 08:20
Closed via https://github.com/bpmn-io/bpmn-js/pull/1578

**Closed by MaxTru** 2022-01-19 08:20 UTC
Labels: bug, needs review, spring cleaning
