### ISSUE TITLE
Label edits not visible in Firefox

### ISSUE THREAD

**Issue by blakespalmer** [bpmn-io/bpmn-js#660] opened 2017-02-02 07:42 UTC
Firefox v44.0.2

Adding labels do not appear in the diagram after editing. You can edit the elements label again and it will display the previous entered value but it looks like they are not properly saved against the diagram.

You can open up an existing model that has labels, but any further edits to those labels will not be saved. 

Also when exporting the ".bpmn" file the newly added labels are not saved.

Expected:
``` xml
  <bpmn:process id="Process_1" isExecutable="false">
    <bpmn:startEvent id="StartEvent_1" name="Start" />
  </bpmn:process>`
```
Actual:
``` xml
  <bpmn:process id="Process_1" isExecutable="false">
    <bpmn:startEvent id="StartEvent_1" />
  </bpmn:process>
```

__Screenshots__

![firefox_lables_not_saving_2017-02-02](https://cloud.githubusercontent.com/assets/2830003/22540715/7f08aff2-e96d-11e6-8322-fda6b650a993.gif)

Another one, showing label / adding, editing results on Firefox:

![image](https://cloud.githubusercontent.com/assets/58601/22587729/3191e540-ea03-11e6-8c91-9b1e6f89c836.png)

**Comment by nikku** [comment] 2017-02-02 08:04
Please provide more context, I cannot reproduce your issue on Firefox / [demo.bpmn.io](demo.bpmn.io/s/start).

**Comment by blakespalmer** [comment] 2017-02-03 00:02
Apologies for not giving enough information & thanks for the response. I have updated my Firefox to v47.0.2 and tried again. I am having a similar problem but not exactly the same.

I am using http://demo.bpmn.io/

1. Clicking "new Diagram"
2. The diagram starts with a StartEvent
3. I double click the StartEvent to add a label.
4. When I press enter to confirm, the label is not placed underneath the start event. Instead it is placed underneath and to the right. 
5. I can not select the label to move it back underneath the StartEvent.
6. If I click and drag the start event object, the label then moves to the correct position and is now selectable.
7. When exporting the ".bpmn" file, the labels are always correctly stored.

I am noticing the same issue in Internet Explorer v11.0.9600.18537CO

Please let me know if you have more trouble reproducing, and let me know what I can do to help.

![firefox_v v47 0 2_labelsinwrongposition_2017-02-03](https://cloud.githubusercontent.com/assets/2830003/22573310/1dbceb6e-e9f4-11e6-951c-09154965867b.gif)

**Comment by nikku** [comment] 2017-02-03 10:26
I can reproduce your findings. Thanks for reporting.

**Comment by nikku** [comment] 2017-02-07 23:55
Probably addressed by https://github.com/bpmn-io/diagram-js/issues/205.

**Closed** 2017-03-02 10:49 UTC
Labels: browser:Firefox, browser:IE, bug
