### ISSUE TITLE
Sequence Flow Layout Broken After Dropping Element

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js#1178] opened 2019-08-23 09:27 UTC
Dropping any element onto a sequence flow breaks the layout. The docking of the new incoming sequence flow seems to always be the top left corner.

![23-08-_2019_11-24-32](https://user-images.githubusercontent.com/7633572/63582090-b42c1700-c598-11e9-90fd-aacc18d93bb2.gif)

**Comment by nikku** [comment] 2019-08-26 06:13
Which versions of bpmn-js allow you to reproduce this issue?

For me it looks like an unintentional side-effect of https://github.com/bpmn-io/bpmn-js/commit/6aaf816802c9513f629c33ef46f82898f80db999.

**Comment by nikku** [comment] 2019-08-29 12:50
Closed via https://github.com/bpmn-io/bpmn-js/pull/1179.

**Closed by nikku** 2019-08-29 12:50 UTC
Labels: bug, needs review
