### ISSUE TITLE
Confusing behavior of groups with same category value

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-js#1055] opened 2019-05-29 07:25 UTC
__Describe the Bug__

Modification of groups with same referenced `bpmn:CategoryValue` leads to incorrect state.

__Steps to Reproduce__

1. Having two `bpmn:Group` elements with the same referenced `bpmn:CategoryValue`
2. Edit one group's label

Category value modification leads to a situation when one of the labels is incorrect.

![Jul-01-2019 13-07-25](https://user-images.githubusercontent.com/9433996/60431949-50711780-9c01-11e9-9903-cef3c155fc24.gif)

__Expected Behavior__

Modify the labels of all connected groups.

__Environment__

Please complete the following information:

 - Browser: Camunda Modeler with linked `master` branches
 - OS: MacOS
 - Library version: `master`

**Comment by pinussilvestrus** [comment] 2019-05-29 08:14
The missing `label` on the pasted element is caused by the fact we only looking for `businessObject.name` inside the [`LabelBehavior`](https://github.com/bpmn-io/bpmn-js/blob/master/lib/features/modeling/behavior/LabelBehavior.js#L86). We should also check for `categoryValueRef`, maybe just using `LabelUtil#getLabel`.

For the second problem, we have to discuss the two options we have. I'd say just go for modifying all connected groups.

**Comment by nikku** [comment] 2019-05-29 08:28
I agree on both points :+1:

**Comment by pinussilvestrus** [comment] 2019-05-29 08:53
I created a small solution sketch for this: https://github.com/bpmn-io/bpmn-js/tree/1055-copy-groups

We can consider doing it this way when we tackle this problem in (near) future.

**Comment by pinussilvestrus** [comment] 2019-07-01 07:08
I'll try out the approach mentioned [in this comment](https://github.com/camunda/camunda-modeler/issues/1417#issuecomment-506730824).

**Comment by pinussilvestrus** [comment] 2019-07-01 11:10
Update the description to

* exclude the Copy & Paste problem which is stated in camunda/camunda-modeler#1417
* state out the problem with `bpmn:Group` elements with same referenced `bpmn:CategoryValue`

**Comment by nikku** [comment] 2019-08-05 08:50
I believe this is being fixed or will be fixed with new copy + paste behavior.

Happy to re-open this, if we see it still being broken.

**Closed by nikku** 2019-08-05 08:50 UTC
Labels: backlog, bug, modeling
